# Generated by Django 5.0.7 on 2024-07-25 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PitchReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pitch_type', models.CharField(max_length=100)),
                ('weather_conditions', models.CharField(max_length=100)),
                ('soil_type', models.CharField(max_length=100)),
                ('grass_cover', models.CharField(max_length=100)),
                ('dryness', models.CharField(max_length=100)),
                ('cracks', models.CharField(max_length=100)),
                ('bounce', models.CharField(max_length=100)),
                ('turn', models.CharField(max_length=100)),
                ('seam_movement', models.CharField(max_length=100)),
                ('moisture_levels', models.CharField(max_length=100)),
                ('additional_notes', models.TextField()),
            ],
        ),
    ]
